FROM python:3.9.12
LABEL maintainer="Jiahao Zhang <jiahao.zhang@anu.edu.au>"

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install --no-cache-dir gunicorn
RUN rm /requirements.txt

RUN mkdir -p infuencemap/webapp/
COPY webapp /infuencemap/webapp/
COPY core /infuencemap/core/
COPY graph /infuencemap/graph/

WORKDIR /infuencemap/
EXPOSE 8001
ENTRYPOINT ["gunicorn", "-w 8", "-b 0.0.0.0:8001", "webapp:flask_app"]
