FROM python:3.9.12
LABEL maintainer="Jiahao Zhang <jiahao.zhang@anu.edu.au>"

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install --no-cache-dir gunicorn
RUN rm /requirements.txt

RUN mkdir -p /influencemap
COPY webapp /influencemap/webapp/
COPY core /influencemap/core/
COPY graph /influencemap/graph/

WORKDIR /influencemap/
EXPOSE 8001
ENV KONIGSBERG_URL="url_to_konigsberg"
ENV ELASTICSEARCH_URL="url_to_elasticsearch"
ENV GUNICORN_CMD_ARGS="--workers 32 --timeout 90 --graceful-timeout 90 --bind 0.0.0.0:8001"
RUN echo "#!/bin/bash \n gunicorn $GUNICORN_CMD_ARGS webapp:flask_app" > ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
