FROM python:3.9.12
LABEL maintainer="Jiahao Zhang <jiahao.zhang@anu.edu.au>"

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install --no-cache-dir gunicorn
RUN rm /requirements.txt

RUN mkdir -p /influencemap
COPY webapp /influencemap/webapp/
COPY core /influencemap/core/
COPY graph /influencemap/graph/

WORKDIR /influencemap/
EXPOSE 8001
ENTRYPOINT ["gunicorn", "-w 8", "-b 0.0.0.0:8001", "webapp:flask_app"]
